### PR TITLE
Initial commit of a skeleton build of OOPS+IODA+BUFR Query

### PR DESCRIPTION
**Pull request by CoryMartin-NOAA**
What the title says.

### CODE REVIEW

**Comment by emilyhcliu** [comment]
@CoryMartin-NOAA I see that you come up with a name: obsForge.  What does it mean?  
Thanks for working on this.  I will take a look today.

**Comment by CoryMartin-NOAA** [comment]
ChatGPT suggested it, as we "forge" or create new observations

**Comment by guillaumevernieres** [comment]
it's got a lord of the ring vibe ... Gollume likes it!

**Comment by CoryMartin-NOAA** [comment]
@emilyhcliu we will probably have to build up some scripts/testing framework but this should be enough to get people started

**Comment by emilyhcliu** [comment]
> @emilyhcliu we will probably have to build up some scripts/testing framework but this should be enough to get people started

@CoryMartin-NOAA Many thanks for coming up with this repository.  Here is what the obsproc re-engineering team will do:
1. Add mapping (required) file and Python script (optional) for each data type in SPOC that can handle the use of them in backend (create in memory) or in the frontend (create netCDF files) in SPOC. --- We are writing the Python in a way that one python code can handle both cases (memory and file).  
2. Add test (configuration and script) in obsForge for each data type.  

I will implement satwind in steps 1 and 2 as an example over this weekend.
Then, I will set up a meeting with you and Ron next week to see if you have any suggestions for improvement.

**Comment by emilyhcliu** [comment]
@CoryMartin-NOAA 
I checked out obsForge with your feature/initial branch.
I tried to build it with ./build.sh --- this failed at checking out repositories from the bundle
Then I tried to load the modules first:
```
module use /work/noaa/da/eliu/HERCULES/EMC-obsForge/obsForge/modulefiles/
module load obsforge/hercules.intel
```
This failed at the same point.  

```
-- Adding bundle project jedicmake
CMake Error at /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.7.0/envs/ue-intel/install/intel/2021.9.0/ecbuild-3.7.2-ljy2rx3/share/ecbuild/cmake/ecbuild_log.cmake:190 (message):
  CRITICAL - Source directory
  '/work/noaa/da/eliu/HERCULES/EMC-obsForge/obsForge/bundle/jedicmake' for
  subproject 'jedicmake' does not exist or does not contain a CMakeLists.txt
  file.
Call Stack (most recent call first):
  /work/noaa/epic/role-epic/spack-stack/hercules/spack-stack-1.7.0/envs/ue-intel/install/intel/2021.9.0/ecbuild-3.7.2-ljy2rx3/share/ecbuild/cmake/ecbuild_bundle.cmake:166 (ecbuild_critical)
  CMakeLists.txt:39 (ecbuild_bundle)


-- Configuring incomplete, errors occurred!
See also "/work/noaa/da/eliu/HERCULES/EMC-obsForge/obsForge/build/CMakeFiles/CMakeOutput.log".
```
Any suggestion?

**Comment by CoryMartin-NOAA** [comment]
@emilyhcliu let me try a fresh clone, I may not have included `jedicmake` correctly as a submodule.

You did do `git clone --recursive` right?

**Comment by emilyhcliu** [comment]
> @emilyhcliu let me try a fresh clone, I may not have included `jedicmake` correctly as a submodule.
> 
> You did do `git clone --recursive` right?

Yes, I did use --recursive to clone the develop of obsForge.

**Comment by emilyhcliu** [comment]
> > @emilyhcliu let me try a fresh clone, I may not have included `jedicmake` correctly as a submodule.
> > You did do `git clone --recursive` right?
> 
> Yes, I did use --recursive to clone the develop of obsForge.

git clone --recursive https://github.com/NOAA-EMC/obsForge

**Comment by CoryMartin-NOAA** [comment]
oh, because the submodules are not in develop yet, when you checkout the feature branch you probably needed to do soemthing like `git submodule update --init --recursive`.

Doing this worked for me on Hercules just now:
`git clone --recursive https://github.com/noaa-emc/obsforge -b feature/initial`

**Comment by emilyhcliu** [comment]
I checked out obsForge featur/initial and built it.  
It was built successfully.  The executables and libraries from obsForge were used to test bufr-query and IODA bufr/script backend for satellite wind GOES AMVs.  

Approved!!

**Review by emilyhcliu — APPROVED** [review]

**Pull request merged**
